# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mat_especialidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historia_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_historia', models.DateTimeField(verbose_name='Fecha de Creacion')),
                ('diagnostico', models.CharField(max_length=500)),
                ('tratamiento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Turno')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gturnos.Persona')),
                ('mat_profesional', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Especialidad')),
            ],
            bases=('gturnos.persona',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gturnos.Persona')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Alta Como paciente')),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('perimetro_enc', models.IntegerField()),
            ],
            bases=('gturnos.persona',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Persona'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Tipo_Usuario'),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Usuario'),
        ),
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Paciente'),
        ),
        migrations.AddField(
            model_name='historia_medica',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
        migrations.AddField(
            model_name='historia_medica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Paciente'),
        ),
    ]
