# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gturnos', '0003_auto_20160429_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nac',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
