# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gturnos', '0004_auto_20160429_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Med_Esp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_especialidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='mat_especialidad',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='rel_med_esp',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Especialidad'),
        ),
        migrations.AddField(
            model_name='rel_med_esp',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gturnos.Medico'),
        ),
    ]
