# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gturnos', '0005_auto_20160502_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia_medica',
            name='fecha_historia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
